version: 2
jobs:
  build:
    docker:
      - image: golang:1.12-alpine

    working_directory: /go/src/github.com/splunk/splunk-cloud-sdk-go

    steps:
      - checkout

      - run:
          name: setup
          command: |
            export CGO_ENABLED=0
            export SKIP_DOWNLOAD_CONFIG=true
            make setup

      - run:
          name: lint
          command: make lint

      - run:
          name: format
          command: make format_check

      - run:
          name: vet
          command: make vet

      - run:
          name: build
          command: make build

      - run:
          name: unittest
          command: make test_unit

experimental:
  notify:
    branches:
      only:
        - master

